### ISSUE TITLE
Поправить жест "свайп"

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/annagrab.ru#32]
На мобильном устройства при перемотке сайта annagrab.ru вниз жест "свайп" не работает на красном блоке (свайп вправо влево работает). Вот тут:
<img width="378" alt="Screenshot 2021-09-21 at 22 14 06" src="https://user-images.githubusercontent.com/4641125/134240978-52cc43cd-bdcb-46dd-91af-ab575d5b4ca2.png">
 
А вот на сайте Дом Китобоя свайп классно работает во все 4 стороны, вот тут (https://domkitoboya.ru/rent/):  
<img width="382" alt="Screenshot 2021-09-21 at 22 17 49" src="https://user-images.githubusercontent.com/4641125/134241444-38375a6d-7944-4be9-a1ff-ccd14e61d14c.png">

Добавить свайп вниз-вверх на красном блоке.

**Comment by alisabox** [comment]
Может помочь изменение переменной threshold в меньшую сторону.

**Comment by VadimCpp** [comment]
Видео того как не работает прокрутка сайта на мобильном устройстве обратить внимание на жесты свайп вверх-вних:

https://user-images.githubusercontent.com/4641125/134799836-b2f1dc06-919e-455f-9f0e-e5be9921a345.mp4

**Comment by VadimCpp** [comment]
Я убрал одну строку (см коммит выше), которая прерывает обработку события и не передает его боле высокоуровневым компонентам для обработки. И все заработало:

https://user-images.githubusercontent.com/4641125/134800395-5f1f5e89-7e17-41a6-b45b-e3a171fd9a94.mp4
