### ISSUE TITLE
Добавить ссылки в слайдер

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/annagrab.ru#41]
![telegram-cloud-photo-size-2-5355123168236385310-y](https://user-images.githubusercontent.com/4641125/137027438-35a9a1af-875a-4c85-8a52-d898175aa016.jpg)

Отзыв клиента:
"Попытался перейти на сайт в слайдере, но ссылка не кликабельна, расстроился."

Требуется в слайдер добавить ссылки, их цвет должен совпадать с текущим цветом текста

**Comment by alisabox** [comment]
Ссылка на отзыве Ester Models должна вести на сайт http://ester-models.tilda.ws/ ?
