### ISSUE TITLE
Добавить раздел "контакты"

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/annagrab.ru#70]
Чтобы увидеть контакты, необходимо промотать вниз: 

<img width="457" alt="Screenshot 2022-02-08 at 15 19 52" src="https://user-images.githubusercontent.com/4641125/152995134-3343fb3d-e5bf-42c5-9881-0c00f9379632.png">

Продублировать блок контакты под этим блоком:
<img width="681" alt="Screenshot 2022-02-08 at 15 20 28" src="https://user-images.githubusercontent.com/4641125/152995253-02d79696-c258-41ba-adde-9ce913d94fe3.png">

Стилизацию нового блока сделать в светлом тоне. Иконки сделать разноцветными - по цветам соцсетей

**Comment by open-ssl** [comment]
Взял

**Comment by VadimCpp** [comment]
Теперь выглядит так:

<img width="354" alt="Screenshot 2022-02-16 at 22 15 38" src="https://user-images.githubusercontent.com/4641125/154339701-39e90f85-0368-4449-ad84-3fc7f217ce78.png">

@open-ssl спасибо за вклад в open source
